### ISSUE TITLE
CSS Selectors Support

### ISSUE THREAD

**Issue by sibprogrammer** [sibprogrammer/xq#16]
### Problem Statement

The XPath query language is less popular and more verbose compared to CSS selectors.

### Expected Result

It is possible to query content using a CSS selector. 

### Additional Info

The corresponding thread: https://news.ycombinator.com/item?id=33573240

**Comment by odanoburu** [comment]
Can you implement CSS selectors for custom elements? https://html.spec.whatwg.org/multipage/custom-elements.html
