### ISSUE TITLE
HTML Multiline comments

### ISSUE THREAD

**Issue by yene** [sibprogrammer/xq#18]
Small thing I noticed, for HTML multiline comments the first line gets indented, the other lines stay.
Maybe multiline comments should be ignored

raw
```html
<body>
<!--
  <p>hello</p>
-->
<p>world</p>
</body>
```

formatted
```html
  <body>
    <!--
  <p>hello</p>
-->
    <p>world</p>
  </body>

```

**Comment by sibprogrammer** [comment]
@yene thank you for your report! Multiline comments should be indented as well.
