### ISSUE TITLE
xq replaces &quot; with " when it can cause issues:

### ISSUE THREAD

**Issue by nworms** [sibprogrammer/xq#22]
Original text:

      <SEQUENCE mandatory="FALSE" precondition="GetParam(&quot;HASH_VALUE_SHARING_MODE&quot;) != 1">

After running xq:

        <SEQUENCE mandatory="FALSE" precondition="GetParam("HASH_VALUE_SHARING_MODE") == 1">

The original place of &quot; is to ensure there is no closure of the " opened before Get Param.
The conversion of &quot; to " causes issues

**Comment by nworms** [comment]
Similar with &lt; that we use instead of < that is confused as part of XML format.

and &amp; that we use instead of &

**Comment by sibprogrammer** [comment]
@nworms thank you for your report. I think it's a little bit controversial. The main intention was to have a utility that shows XML content that is easy to read by humans (e.g. with proper formatting, syntax highlighting and etc.)

**Comment by sibprogrammer** [comment]
A brief check shows that it's a behavior of XML standard library in Go that is not easy to override or influence somehow: https://github.com/golang/go/blob/master/src/encoding/xml/xml.go#L1086
It looks like a good candidate to be reported as an issue to the Golang project.

**Comment by nworms** [comment]
Go has support to add the escaped version of the problematic characters using:

xml.EscapeText

I understand now your motivation to use xq to have a more human readable version of XML.

May be (in the future) add a command line option to have it be both be human and machine readable and it that case you will use xml.EscapeText for the attribute values.

**Comment by sibprogrammer** [comment]
@nworms Thank you for your suggestion. I'll apply the corresponding fix.
