### ISSUE TITLE
AIX build / binary

### ISSUE THREAD

**Issue by bmarwell** [sibprogrammer/xq#32]
**Problem Statement**

I would like to request a convenience binary for AIX, powerpc64 (ppc64)

**Expected Result**

[Release](https://github.com/sibprogrammer/xq/releases/tag/v1.1.4) contains an additional artifact for AIX-ppc64.

**Comment by bmarwell** [comment]
I am not a go developer, but building for AIX was surprisingly easy on my Mac M1:

```
$ env GOOS=aix  GOARCH=ppc64 go build -o xq.aix.ppc64
[...]
$ file xq.aix.ppc64
xq.aix.ppc64: 64-bit XCOFF executable or object module
```

**Comment by sibprogrammer** [comment]
I'm not sure if it is worth doing it by default. Because it's relatively easy to recompile manually, and it seems the aix/ppc64 is pretty exotic architecture. I am even surprised to see it nowadays.

**Comment by bmarwell** [comment]
Used in big companies... IBM sells quite a lot of power architecture. In fact, AIX runs only on PPC64. 

I'll see if I can create a local build pipeline myself, but not being a go user and needing some firewall settings modified, I thought I'd ask first. 😉

**Comment by sibprogrammer** [comment]
Ok, let it be :) The corresponding build will be available in the next release.

**Comment by bmarwell** [comment]
Thanks! If download numbers are low, I wouldn't mind if you took it down again. Now that I learned how easy it is to compile for other platforms, it is not a hard work. I would only need to setup a proxy, after all.

Thanks a lot!
