### ISSUE TITLE
Please rename project

### ISSUE THREAD

**Issue by otheus** [sibprogrammer/xq#38]
I'm sure this project was done with love and is very useful, but it is unfortunately the name of this project implies a certain kinship and functional equivalency to `jq` and `yq`.  I propose merging the tool with those projects to avoid community confusion and frustration. Note: `yq` already parses XML.

**Comment by sibprogrammer** [comment]
The initial goal of xq was to provide colorful and pretty formatted XML content. The objectives of other projects are different.
