### ISSUE TITLE
Support --indent 0

### ISSUE THREAD

**Issue by jappaleinen** [sibprogrammer/xq#41]
**Problem Statement**

Today, the flag `--indent` is limited to values 1-8.

In some cases, it also makes sense to use indentation 0, further compacting the resulting xml...

**Expected Result**

```
<?xml version="1.0"?>
<simple>
<element_1>value 1</element_1>
<element_2>value 2</element_2>
</simple>
```

**Comment by sibprogrammer** [comment]
Ok, let it be.
