### ISSUE TITLE
Add new command line flag -es / --element-separators

### ISSUE THREAD

**Issue by jappaleinen** [sibprogrammer/xq#43]
** Problem Statement

Today, elements are separated with a single line feed.
One use case when working with multiple xml documents streamed to console is to get each document on a single line, allowing to pipe result to standard command line tools of interest such as simple grep for selecting / filtering documents.
Also, element separation of 0 would produce the most compact xml possible (in combination with --indent 0 at least).

Adding a new flag `-es` / `--element-separators` with a numeral 0-n (default 1 for backwards compatibility) in a similar way as `--indent` is currently working.

** Expected Result

```
# Current
➜ echo $' <element>  <child/>  </element>  ' | xq
<element>
  <child/>
</element>

➜ echo $'  <element>  <child/>  </element>  ' | xq -es 0 --indent 0
<element><child/></element>
```

**Comment by sibprogrammer** [comment]
I don't want to clutter the interface with additional options if it's possible to avoid them. So I decided to reuse `--indent 0` for compact representation.
