### ISSUE TITLE
"xq --version" outputs "xq version 0.0.0 (unknown, 000000)"

### ISSUE THREAD

**Issue by scfc** [sibprogrammer/xq#44]
At least on Debian Bookworm:

    root@a72bc73c7676:/# dpkg-query -W xq
    xq      1.0.0-2+b5
    root@a72bc73c7676:/# xq --version
    xq version 0.0.0 (unknown, 000000)
    root@a72bc73c7676:/#

and Fedora 38:

    [root@1986a337ee90 /]# rpm -q xq
    xq-1.1.4-1.fc38.x86_64
    [root@1986a337ee90 /]# xq --version
    xq version 0.0.0 (unknown, 000000)
    [root@1986a337ee90 /]#

`xq --version` just outputs `xq version 0.0.0 (unknown, 000000)`.  I don't know whether this is a bug in `xq` or the packaging in both distributions is missing some bit.

**Comment by sibprogrammer** [comment]
OS vendors do the packaging in their own ways. Unfortunately, the information about the version is lost in such cases. I tried to analyze a couple of packages, but it seems there is no straightforward and robust way. So, I will embed the version information into the binary. It will be some sort of "duplication" of the goreleaser automatic procedure though.

**Comment by mikelolasagasti** [comment]
Packages like `gh` or `doctl` set version using `ldflags`. 

https://github.com/cli/cli/blob/trunk/.goreleaser.yml#L36C47-L36C56
https://github.com/digitalocean/doctl/blob/main/.goreleaser.yml#L11

I package both for Fedora and set the correct ldflags:

https://src.fedoraproject.org/rpms/gh/blob/rawhide/f/gh.spec#_52
https://src.fedoraproject.org/rpms/doctl/blob/rawhide/f/doctl.spec#_44

If `xq` can have a similar approach, it would be a distro-friendly change.

**Comment by sibprogrammer** [comment]
`xq` accepts LDFLAGS as well. See https://github.com/Homebrew/homebrew-core/blob/0a8a9383afe6a635c6f2dc50ca0cb487d3ec5ebf/Formula/x/xq.rb#L23
The problem is the majority of Linux distro packages are prepared by community members and I need to discover the location of the package specs, how to contribute, and etc.

**Comment by mikelolasagasti** [comment]
I'll take care of Fedora.

I usually check `Makefile` or `.goreleaser.yml` file to see how this is handled by the project, but as I found 0 references to ldflags in the code, then I just think it's not possible.

**Comment by sibprogrammer** [comment]
> .goreleaser.yml file to see how this is handled by the project, but as I found 0 references

GoRelease has a default for ldflags: https://goreleaser.com/cookbooks/using-main.version/ So it's not necessary to set it explicitly in the `.goreleaser.yml`
