### ISSUE TITLE
xq output missing

### ISSUE THREAD

**Issue by matthiasbock** [sibprogrammer/xq#52]
**Problem Statement**

xq does not print proper output when invoked with '-e' or '-x'.

**Steps to Reproduce**

I tried invoking xq with '-e' or '-x' on a Debian Linux amd64 machine using the current stable Debian package (1.0.0-2) as well as the installer mentioned in the README (1.2.1, 2023-07-09T13:37:33Z, 8ed07bdd6390e64f126abb832bcab0da317f7f34), but get only empty output:

~~~sh
$ xq -e //svg test.svg

$ xq -x //svg test.svg

$ xq -e '//svg' test.svg

$ xq -x '//svg' test.svg

$ xq -x '//*' test.svg






~~~

Without a query the file is properly printed incl. syntax highlighting:

~~~sh
$ xq test.svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg:svg width="181.5pt" height="28.34766pt" viewBox=...
~~~

**Actual Result**

It seems, regardless of the query, xq, when invoked, does not print any text to the console.
Although, the amount of line feed characters (0x0A) seems to depend on the actual query (or the respective result).
Maybe there is a problem in the respective results printing statement?

~~~sh
$ xq -x '//*' test.svg | hexdump -C
00000000  0a 0a 0a 0a 0a 0a 0a 0a  0a 0a 0a 0a 0a 0a 0a 0a  |................|
*
00001ef0  0a                                                |.|
00001ef1
~~~

(I thought, I just saw space characters (0x20) as well, but can't reproduce that now.)

**Expected Result**

xq should print DOM elements to stdout according to the given query.

**Comment by sibprogrammer** [comment]
> xq should print DOM elements to stdout according to the given query.

In fact, it doesn't :) It prints text node content. I expect your SVG file to have only text nodes with spaces. Anyway, please attach to this issue to make things a little bit more clear.

**Comment by sibprogrammer** [comment]
By default, `xq` tries to print the text content. If you want to see DOM elements, use the `-n` flag. Here is an example:
```
$ xq -x "//defs" -n test.svg
<defs id="defs4">
  <path id="box1" d="m0 0h77v210h-77z" stroke="#000" stroke-width="2"/>
  <path id="box2" d="m0 0h77v60h-77z" stroke="#000" stroke-width="2"/>
</defs>
```
