### ISSUE TITLE
invalid output for (some?) nested tags

### ISSUE THREAD

**Issue by tmancill** [sibprogrammer/xq#57]
Hi, first of all, thank you for writing and sharing `xq`.

**Problem Statement**

I encountered this while using `xq` to prettify a [VoiceXML](https://www.w3.org/TR/voicexml21/) document, but it occurs with a trivial document as well.  The following occurs with xq version 1.2.1 and 1.2.2.  I haven't tested older versions to see if might be a regression.

**Steps to Reproduce**

```sh
$ cat << EOF > ./in.xml
<?xml version="1.0" encoding="UTF-8"?>
<foo>
    <bar event="myevent">
      <baz>event seen: <value expr="event"/></baz>
    </bar>
</foo>
EOF
```

Verify that the input doc is valid:
```sh
$ xmllint --noout in.xml && echo VALID
VALID
```

Use `xq` to format the input document:

```sh
$ cat in.xml | xq | tee -a out.xml
<?xml version="1.0" encoding="UTF-8"?>
<foo>
  <bar event="myevent">
    <baz>event seen:
      <value expr="event"</value>>
    </baz>
  </bar>
</foo>
```

**Actual Result**

The output of `xq` is not well-formed.  See the output above and note that `<value expr="event"</value>>` no longer parses.

```sh
$ xmllint out.xml
out.xml:5: parser error : attributes construct error
      <value expr="event"</value>>
                         ^
out.xml:5: parser error : Couldn't find end of Start Tag value line 5
      <value expr="event"</value>>
...                         ^
```

**Expected Result**

Well-formed XML in out.xml.

**Comment by sibprogrammer** [comment]
@tmancill Thank you for the interesting test case!
