### ISSUE TITLE
Does XQ support concat, and if so, how in the hell does it work?

### ISSUE THREAD

**Issue by DCameronMauch** [sibprogrammer/xq#67]
**Problem Statement**

Can't figure out how to use concat, if even supported.  This is the best example I have found, and it produces no results:  https://scrapfly.io/blog/how-to-join-values-in-xpath/

**Expected Result**

From the article above, I expect to see the output the articles says I should see.

**Comment by DCameronMauch** [comment]
`cameron@CameronMacBookPro latest % cat example.xml
<html>
  <div>
    <h2>Coffee</h2>
    <span data-currency="USD">4.69</span>
  </div>
</html>
cameron@CameronMacBookPro latest % cat example.xml | xq -x '//div/concat(h2, " - ", span, span/@data-currency)'
cameron@CameronMacBookPro latest %`

**Comment by sibprogrammer** [comment]
Unfortunately, it doesn't work as intended. I'll take a look at how to workaround the problem.

**Comment by DCameronMauch** [comment]
Thank you!

**Comment by sibprogrammer** [comment]
Now it's possible to use some popular functions. However, the support has some limitations. One of them is that the function will not work inside the selector but works well on the top level. It means you should use something like that:
```
$ cat example.xml | ./xq -x 'concat(//div/h2, " - ", //div/span, //div/span/@data-currency)'
Coffee - 4.69USD
```

**Comment by DCameronMauch** [comment]
When will this be generally available?  I tried it just now, with version 1.2.3, and still getting no results.

**Comment by sibprogrammer** [comment]
The issue was addressed in the master branch, which points to 1.2.4 (see https://github.com/sibprogrammer/xq/blob/master/version) It is not released yet. But I think I'll release it today or tomorrow.

**Comment by DCameronMauch** [comment]
Thanks again!

**Comment by andig** [comment]
Is this also possible when using CSS selectors?
