### ISSUE TITLE
Unrecognized HTML entity: `&copy;` while running xq command using `curl` command

### ISSUE THREAD

**Issue by lulunac27a** [sibprogrammer/xq#71]
**Problem Statement**

I got an error while using `curl` command to curl HTML/XML webpages:
`xq: Error running jq: ExpatError: undefined entity &copy;`

**Steps to Reproduce**

Add custom XML entities using `<!ENTITY name "value">` like `<!ENTITY copy "©">`

**Actual Result**

`xq: Error running jq: ExpatError: undefined entity &copy;`

**Expected Result**

Should successfully pretty print XML output in JSON format including the copyright sign `&copy;` (©)

**Comment by sibprogrammer** [comment]
It seems like you're talking about another project: https://github.com/kislyuk/yq (it also installs the binary called xq)
